#
# Cookbook Name:: zabbix
# Attributes:: default
#
# Copyright 2011, LimeLight Networks
 
default.zabbix.role = [ "agent" ]
default.zabbix.install_path = "/opt/zabbix"

# TODO: The list should be generated by search withing agent recipe. 
# We might want to use IPs to bypass name resolution.
default.zabbix.agent.servers = ["zabbix.delve.me","vps-017.phx2.llnw.net"]
default.zabbix.agent.version = "1.8.5" 
default.zabbix.agent.timeout = 5 
default.zabbix.agent.start_agents = 3 
default.zabbix.agent.debug_level = 2
